name: Build LaTeX PDFs

on:
  push:
    branches: [ main, master ]
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install TeX Live minimal
        run: |
          sudo apt-get update
          sudo apt-get install -y --no-install-recommends \
            texlive-latex-recommended texlive-latex-extra texlive-fonts-recommended \
            texlive-fonts-extra texlive-luatex texlive-xetex latexmk

      - name: Build LaTeX documents
        run: |
          chmod +x Technical/scripts/build-latex.sh
          ./Technical/scripts/build-latex.sh --outdir Output/pdfs

      - name: Upload PDFs
        uses: actions/upload-artifact@v4
        with:
          name: latex-pdfs
          path: Output/pdfs/**/**.pdf
